Alias /repos/el7/x86_64 /stor/repos/el7/x86_64
<Directory "/stor/repos/el7/x86_64">
 Options Indexes FollowSymLinks
 AllowOverride All
 Require all granted
</Directory>

Alias /repos/el8/x86_64 /stor/repos/el8/x86_64
<Directory "/stor/repos/el8/x86_64">
 Options Indexes FollowSymLinks
 AllowOverride All
 Require all granted
</Directory>

Alias /repos/rhel7/x86_64 /stor/repos/rhel7/x86_64
<Directory "/stor/repos/rhel7/x86_64">
 Options Indexes FollowSymLinks
 AllowOverride All
 Require all granted
</Directory>
